name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

env:
  DEVELOPER_DIR: /Applications/Xcode_11.app

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install swiftlint
        run: HOMEBREW_NO_INSTALL_CLEANUP=1 brew install swiftlint
      - name: xcodebuild test
        run: set -o pipefail && xcodebuild test -scheme NicerTouchBar -destination "platform=macOS" | xcpretty